import EcoSystemHero from "@/components/EcosystemHero/EcoSystemHero";
import React from "react";
import Head from "next/head";
import Filter from "@/components/Filter/Filter";

const ecosystem = () => {
  return (
    <>
      <Head>
        <title>Ecosystem - BFIC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/icons/favicon.ico" />
      </Head>
      <main>
        <EcoSystemHero />
        <Filter />
      </main>
    </>
  );
};

export default ecosystem;
