import React from "react";
import Head from "next/head";
import ComminityHero from "@/components/ComminityHero/ComminityHero";
import Blogs from "@/components/Blogs/Blogs";
import SocailMedia from "@/components/SocailMedia/SocailMedia";
import { blogs } from "@/utils/constants";

const community = () => {
  return (
    <>
      <Head>
        <title>Community</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/icons/favicon.ico" />
      </Head>
      <main>
        <ComminityHero />
        {blogs.map((item) => {
          return (
            <Blogs
              details={item.details}
              key={item.id}
              titleBlogs={item.title}
            />
          );
        })}

        <SocailMedia />
      </main>
    </>
  );
};

export default community;
